version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: "monthly"
    groups:
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "monthly"
    groups:
      actions-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
