# This file contains all available configuration options
# with their default values.

# all available settings of specific linters
linters-settings:
  modules-download-mode: vendor
  dupl:
    threshold: 400
  funlen:
    lines: 150
    statements: 100
  gocritic:
    enabled-tags:
      - performance
    disabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - style
  gocyclo:
    min-complexity: 25
  misspell:
    locale: US
  lll:
    line-length: 140
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
    # - name: increment-decrement
      - name: error-return
      - name: error-naming
      - name: exported
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
    # - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: unreachable-code
      - name: redefines-builtin-id

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - copyloopvar
    - funlen
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
  # - lll
    - stylecheck
    - gosimple
    - whitespace

run:
  go: 1.18
  timeout: 5m

severity:
  default-severity: error
