// Code generated by MockGen. DO NOT EDIT.
// Source: idcs.go

// Package app is a generated GoMock package.
package app

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	node_state "github.com/yandex/mysync/internal/app/node_state"
	mysql "github.com/yandex/mysync/internal/mysql"
)

// MockIAppDCS is a mock of IAppDCS interface.
type MockIAppDCS struct {
	ctrl     *gomock.Controller
	recorder *MockIAppDCSMockRecorder
}

// MockIAppDCSMockRecorder is the mock recorder for MockIAppDCS.
type MockIAppDCSMockRecorder struct {
	mock *MockIAppDCS
}

// NewMockIAppDCS creates a new mock instance.
func NewMockIAppDCS(ctrl *gomock.Controller) *MockIAppDCS {
	mock := &MockIAppDCS{ctrl: ctrl}
	mock.recorder = &MockIAppDCSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAppDCS) EXPECT() *MockIAppDCSMockRecorder {
	return m.recorder
}

// ClearRecovery mocks base method.
func (m *MockIAppDCS) ClearRecovery(host string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearRecovery", host)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearRecovery indicates an expected call of ClearRecovery.
func (mr *MockIAppDCSMockRecorder) ClearRecovery(host interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearRecovery", reflect.TypeOf((*MockIAppDCS)(nil).ClearRecovery), host)
}

// CreateCurrentSwitchover mocks base method.
func (m *MockIAppDCS) CreateCurrentSwitchover(switchover *Switchover) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCurrentSwitchover", switchover)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCurrentSwitchover indicates an expected call of CreateCurrentSwitchover.
func (mr *MockIAppDCSMockRecorder) CreateCurrentSwitchover(switchover interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCurrentSwitchover", reflect.TypeOf((*MockIAppDCS)(nil).CreateCurrentSwitchover), switchover)
}

// DeleteActiveNodes mocks base method.
func (m *MockIAppDCS) DeleteActiveNodes() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActiveNodes")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteActiveNodes indicates an expected call of DeleteActiveNodes.
func (mr *MockIAppDCSMockRecorder) DeleteActiveNodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActiveNodes", reflect.TypeOf((*MockIAppDCS)(nil).DeleteActiveNodes))
}

// DeleteCurrentSwitchover mocks base method.
func (m *MockIAppDCS) DeleteCurrentSwitchover() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCurrentSwitchover")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCurrentSwitchover indicates an expected call of DeleteCurrentSwitchover.
func (mr *MockIAppDCSMockRecorder) DeleteCurrentSwitchover() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCurrentSwitchover", reflect.TypeOf((*MockIAppDCS)(nil).DeleteCurrentSwitchover))
}

// DeleteMaintenance mocks base method.
func (m *MockIAppDCS) DeleteMaintenance() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMaintenance")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMaintenance indicates an expected call of DeleteMaintenance.
func (mr *MockIAppDCSMockRecorder) DeleteMaintenance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMaintenance", reflect.TypeOf((*MockIAppDCS)(nil).DeleteMaintenance))
}

// FetchCascadeNodeConfigurations mocks base method.
func (m *MockIAppDCS) FetchCascadeNodeConfigurations() (map[string]mysql.CascadeNodeConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCascadeNodeConfigurations")
	ret0, _ := ret[0].(map[string]mysql.CascadeNodeConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCascadeNodeConfigurations indicates an expected call of FetchCascadeNodeConfigurations.
func (mr *MockIAppDCSMockRecorder) FetchCascadeNodeConfigurations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCascadeNodeConfigurations", reflect.TypeOf((*MockIAppDCS)(nil).FetchCascadeNodeConfigurations))
}

// GetActiveNodes mocks base method.
func (m *MockIAppDCS) GetActiveNodes() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveNodes")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveNodes indicates an expected call of GetActiveNodes.
func (mr *MockIAppDCSMockRecorder) GetActiveNodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveNodes", reflect.TypeOf((*MockIAppDCS)(nil).GetActiveNodes))
}

// GetClusterCascadeFqdnsFromDcs mocks base method.
func (m *MockIAppDCS) GetClusterCascadeFqdnsFromDcs() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterCascadeFqdnsFromDcs")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterCascadeFqdnsFromDcs indicates an expected call of GetClusterCascadeFqdnsFromDcs.
func (mr *MockIAppDCSMockRecorder) GetClusterCascadeFqdnsFromDcs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterCascadeFqdnsFromDcs", reflect.TypeOf((*MockIAppDCS)(nil).GetClusterCascadeFqdnsFromDcs))
}

// GetCurrentSwitchover mocks base method.
func (m *MockIAppDCS) GetCurrentSwitchover(switchover *Switchover) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentSwitchover", switchover)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetCurrentSwitchover indicates an expected call of GetCurrentSwitchover.
func (mr *MockIAppDCSMockRecorder) GetCurrentSwitchover(switchover interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentSwitchover", reflect.TypeOf((*MockIAppDCS)(nil).GetCurrentSwitchover), switchover)
}

// GetHealthState mocks base method.
func (m *MockIAppDCS) GetHealthState(host string, state *node_state.NodeState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHealthState", host, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetHealthState indicates an expected call of GetHealthState.
func (mr *MockIAppDCSMockRecorder) GetHealthState(host, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHealthState", reflect.TypeOf((*MockIAppDCS)(nil).GetHealthState), host, state)
}

// GetHostsOnRecovery mocks base method.
func (m *MockIAppDCS) GetHostsOnRecovery() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostsOnRecovery")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHostsOnRecovery indicates an expected call of GetHostsOnRecovery.
func (mr *MockIAppDCSMockRecorder) GetHostsOnRecovery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostsOnRecovery", reflect.TypeOf((*MockIAppDCS)(nil).GetHostsOnRecovery))
}

// GetLastRejectedSwitchover mocks base method.
func (m *MockIAppDCS) GetLastRejectedSwitchover(switchover *Switchover) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastRejectedSwitchover", switchover)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetLastRejectedSwitchover indicates an expected call of GetLastRejectedSwitchover.
func (mr *MockIAppDCSMockRecorder) GetLastRejectedSwitchover(switchover interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastRejectedSwitchover", reflect.TypeOf((*MockIAppDCS)(nil).GetLastRejectedSwitchover), switchover)
}

// GetLastShutdownNodeTime mocks base method.
func (m *MockIAppDCS) GetLastShutdownNodeTime() (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastShutdownNodeTime")
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastShutdownNodeTime indicates an expected call of GetLastShutdownNodeTime.
func (mr *MockIAppDCSMockRecorder) GetLastShutdownNodeTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastShutdownNodeTime", reflect.TypeOf((*MockIAppDCS)(nil).GetLastShutdownNodeTime))
}

// GetLastSwitchover mocks base method.
func (m *MockIAppDCS) GetLastSwitchover(switchover *Switchover) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastSwitchover", switchover)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetLastSwitchover indicates an expected call of GetLastSwitchover.
func (mr *MockIAppDCSMockRecorder) GetLastSwitchover(switchover interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastSwitchover", reflect.TypeOf((*MockIAppDCS)(nil).GetLastSwitchover), switchover)
}

// GetMaintenance mocks base method.
func (m *MockIAppDCS) GetMaintenance() (*Maintenance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaintenance")
	ret0, _ := ret[0].(*Maintenance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaintenance indicates an expected call of GetMaintenance.
func (mr *MockIAppDCSMockRecorder) GetMaintenance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaintenance", reflect.TypeOf((*MockIAppDCS)(nil).GetMaintenance))
}

// GetMasterHostFromDcs mocks base method.
func (m *MockIAppDCS) GetMasterHostFromDcs() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMasterHostFromDcs")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMasterHostFromDcs indicates an expected call of GetMasterHostFromDcs.
func (mr *MockIAppDCSMockRecorder) GetMasterHostFromDcs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMasterHostFromDcs", reflect.TypeOf((*MockIAppDCS)(nil).GetMasterHostFromDcs))
}

// GetNodeConfiguration mocks base method.
func (m *MockIAppDCS) GetNodeConfiguration(host string) (mysql.NodeConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeConfiguration", host)
	ret0, _ := ret[0].(mysql.NodeConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeConfiguration indicates an expected call of GetNodeConfiguration.
func (mr *MockIAppDCSMockRecorder) GetNodeConfiguration(host interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeConfiguration", reflect.TypeOf((*MockIAppDCS)(nil).GetNodeConfiguration), host)
}

// GetReplMonTS mocks base method.
func (m *MockIAppDCS) GetReplMonTS() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReplMonTS")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReplMonTS indicates an expected call of GetReplMonTS.
func (mr *MockIAppDCSMockRecorder) GetReplMonTS() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReplMonTS", reflect.TypeOf((*MockIAppDCS)(nil).GetReplMonTS))
}

// GetResetupStatus mocks base method.
func (m *MockIAppDCS) GetResetupStatus(host string) (mysql.ResetupStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResetupStatus", host)
	ret0, _ := ret[0].(mysql.ResetupStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResetupStatus indicates an expected call of GetResetupStatus.
func (mr *MockIAppDCSMockRecorder) GetResetupStatus(host interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResetupStatus", reflect.TypeOf((*MockIAppDCS)(nil).GetResetupStatus), host)
}

// IsRecoveryNeeded mocks base method.
func (m *MockIAppDCS) IsRecoveryNeeded(host string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRecoveryNeeded", host)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRecoveryNeeded indicates an expected call of IsRecoveryNeeded.
func (mr *MockIAppDCSMockRecorder) IsRecoveryNeeded(host interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRecoveryNeeded", reflect.TypeOf((*MockIAppDCS)(nil).IsRecoveryNeeded), host)
}

// IssueFailover mocks base method.
func (m *MockIAppDCS) IssueFailover(master string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueFailover", master)
	ret0, _ := ret[0].(error)
	return ret0
}

// IssueFailover indicates an expected call of IssueFailover.
func (mr *MockIAppDCSMockRecorder) IssueFailover(master interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueFailover", reflect.TypeOf((*MockIAppDCS)(nil).IssueFailover), master)
}

// SetActiveNodes mocks base method.
func (m *MockIAppDCS) SetActiveNodes(nodes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActiveNodes", nodes)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActiveNodes indicates an expected call of SetActiveNodes.
func (mr *MockIAppDCSMockRecorder) SetActiveNodes(nodes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActiveNodes", reflect.TypeOf((*MockIAppDCS)(nil).SetActiveNodes), nodes)
}

// SetCurrentSwitchover mocks base method.
func (m *MockIAppDCS) SetCurrentSwitchover(switchover *Switchover) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCurrentSwitchover", switchover)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCurrentSwitchover indicates an expected call of SetCurrentSwitchover.
func (mr *MockIAppDCSMockRecorder) SetCurrentSwitchover(switchover interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCurrentSwitchover", reflect.TypeOf((*MockIAppDCS)(nil).SetCurrentSwitchover), switchover)
}

// SetHealthState mocks base method.
func (m *MockIAppDCS) SetHealthState(host string, state *node_state.NodeState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHealthState", host, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHealthState indicates an expected call of SetHealthState.
func (mr *MockIAppDCSMockRecorder) SetHealthState(host, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHealthState", reflect.TypeOf((*MockIAppDCS)(nil).SetHealthState), host, state)
}

// SetLastRejectedSwitchover mocks base method.
func (m *MockIAppDCS) SetLastRejectedSwitchover(switchover *Switchover) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastRejectedSwitchover", switchover)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLastRejectedSwitchover indicates an expected call of SetLastRejectedSwitchover.
func (mr *MockIAppDCSMockRecorder) SetLastRejectedSwitchover(switchover interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastRejectedSwitchover", reflect.TypeOf((*MockIAppDCS)(nil).SetLastRejectedSwitchover), switchover)
}

// SetLastSwitchover mocks base method.
func (m *MockIAppDCS) SetLastSwitchover(switchover *Switchover) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastSwitchover", switchover)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLastSwitchover indicates an expected call of SetLastSwitchover.
func (mr *MockIAppDCSMockRecorder) SetLastSwitchover(switchover interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastSwitchover", reflect.TypeOf((*MockIAppDCS)(nil).SetLastSwitchover), switchover)
}

// SetLowSpace mocks base method.
func (m *MockIAppDCS) SetLowSpace(lowSpace bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLowSpace", lowSpace)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLowSpace indicates an expected call of SetLowSpace.
func (mr *MockIAppDCSMockRecorder) SetLowSpace(lowSpace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLowSpace", reflect.TypeOf((*MockIAppDCS)(nil).SetLowSpace), lowSpace)
}

// SetMaintenance mocks base method.
func (m *MockIAppDCS) SetMaintenance(maintenance *Maintenance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMaintenance", maintenance)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMaintenance indicates an expected call of SetMaintenance.
func (mr *MockIAppDCSMockRecorder) SetMaintenance(maintenance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaintenance", reflect.TypeOf((*MockIAppDCS)(nil).SetMaintenance), maintenance)
}

// SetMasterHost mocks base method.
func (m *MockIAppDCS) SetMasterHost(master string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMasterHost", master)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetMasterHost indicates an expected call of SetMasterHost.
func (mr *MockIAppDCSMockRecorder) SetMasterHost(master interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMasterHost", reflect.TypeOf((*MockIAppDCS)(nil).SetMasterHost), master)
}

// SetRecovery mocks base method.
func (m *MockIAppDCS) SetRecovery(host string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRecovery", host)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRecovery indicates an expected call of SetRecovery.
func (mr *MockIAppDCSMockRecorder) SetRecovery(host interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRecovery", reflect.TypeOf((*MockIAppDCS)(nil).SetRecovery), host)
}

// SetReplMonTS mocks base method.
func (m *MockIAppDCS) SetReplMonTS(ts string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReplMonTS", ts)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetReplMonTS indicates an expected call of SetReplMonTS.
func (mr *MockIAppDCSMockRecorder) SetReplMonTS(ts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReplMonTS", reflect.TypeOf((*MockIAppDCS)(nil).SetReplMonTS), ts)
}

// SetResetupStatus mocks base method.
func (m *MockIAppDCS) SetResetupStatus(host string, status bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetResetupStatus", host, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetResetupStatus indicates an expected call of SetResetupStatus.
func (mr *MockIAppDCSMockRecorder) SetResetupStatus(host, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetResetupStatus", reflect.TypeOf((*MockIAppDCS)(nil).SetResetupStatus), host, status)
}

// UpdateLastShutdownNodeTime mocks base method.
func (m *MockIAppDCS) UpdateLastShutdownNodeTime() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastShutdownNodeTime")
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastShutdownNodeTime indicates an expected call of UpdateLastShutdownNodeTime.
func (mr *MockIAppDCSMockRecorder) UpdateLastShutdownNodeTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastShutdownNodeTime", reflect.TypeOf((*MockIAppDCS)(nil).UpdateLastShutdownNodeTime))
}
