// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go

// Package optimization is a generated GoMock package.
package optimization

import (
	gomock "github.com/golang/mock/gomock"
	node_state "github.com/yandex/mysync/internal/app/node_state"
	mysql "github.com/yandex/mysync/internal/mysql"
	reflect "reflect"
)

// MockLogger is a mock of Logger interface
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debugf mocks base method
func (m *MockLogger) Debugf(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debugf", varargs...)
}

// Debugf indicates an expected call of Debugf
func (mr *MockLoggerMockRecorder) Debugf(msg interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugf", reflect.TypeOf((*MockLogger)(nil).Debugf), varargs...)
}

// Infof mocks base method
func (m *MockLogger) Infof(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof
func (mr *MockLoggerMockRecorder) Infof(msg interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*MockLogger)(nil).Infof), varargs...)
}

// Warnf mocks base method
func (m *MockLogger) Warnf(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warnf", varargs...)
}

// Warnf indicates an expected call of Warnf
func (mr *MockLoggerMockRecorder) Warnf(msg interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warnf", reflect.TypeOf((*MockLogger)(nil).Warnf), varargs...)
}

// Errorf mocks base method
func (m *MockLogger) Errorf(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf
func (mr *MockLoggerMockRecorder) Errorf(msg interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockLogger)(nil).Errorf), varargs...)
}

// Fatalf mocks base method
func (m *MockLogger) Fatalf(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatalf", varargs...)
}

// Fatalf indicates an expected call of Fatalf
func (mr *MockLoggerMockRecorder) Fatalf(msg interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatalf", reflect.TypeOf((*MockLogger)(nil).Fatalf), varargs...)
}

// MockDCS is a mock of DCS interface
type MockDCS struct {
	ctrl     *gomock.Controller
	recorder *MockDCSMockRecorder
}

// MockDCSMockRecorder is the mock recorder for MockDCS
type MockDCSMockRecorder struct {
	mock *MockDCS
}

// NewMockDCS creates a new mock instance
func NewMockDCS(ctrl *gomock.Controller) *MockDCS {
	mock := &MockDCS{ctrl: ctrl}
	mock.recorder = &MockDCSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDCS) EXPECT() *MockDCSMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockDCS) Create(path string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", path, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockDCSMockRecorder) Create(path, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDCS)(nil).Create), path, value)
}

// Set mocks base method
func (m *MockDCS) Set(path string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", path, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set
func (mr *MockDCSMockRecorder) Set(path, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockDCS)(nil).Set), path, value)
}

// Get mocks base method
func (m *MockDCS) Get(path string, dest any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", path, dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get
func (mr *MockDCSMockRecorder) Get(path, dest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDCS)(nil).Get), path, dest)
}

// Delete mocks base method
func (m *MockDCS) Delete(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockDCSMockRecorder) Delete(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDCS)(nil).Delete), path)
}

// GetChildren mocks base method
func (m *MockDCS) GetChildren(path string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChildren", path)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChildren indicates an expected call of GetChildren
func (mr *MockDCSMockRecorder) GetChildren(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChildren", reflect.TypeOf((*MockDCS)(nil).GetChildren), path)
}

// MockNodeReplicationController is a mock of NodeReplicationController interface
type MockNodeReplicationController struct {
	ctrl     *gomock.Controller
	recorder *MockNodeReplicationControllerMockRecorder
}

// MockNodeReplicationControllerMockRecorder is the mock recorder for MockNodeReplicationController
type MockNodeReplicationControllerMockRecorder struct {
	mock *MockNodeReplicationController
}

// NewMockNodeReplicationController creates a new mock instance
func NewMockNodeReplicationController(ctrl *gomock.Controller) *MockNodeReplicationController {
	mock := &MockNodeReplicationController{ctrl: ctrl}
	mock.recorder = &MockNodeReplicationControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNodeReplicationController) EXPECT() *MockNodeReplicationControllerMockRecorder {
	return m.recorder
}

// SetReplicationSettings mocks base method
func (m *MockNodeReplicationController) SetReplicationSettings(rs mysql.ReplicationSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReplicationSettings", rs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetReplicationSettings indicates an expected call of SetReplicationSettings
func (mr *MockNodeReplicationControllerMockRecorder) SetReplicationSettings(rs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReplicationSettings", reflect.TypeOf((*MockNodeReplicationController)(nil).SetReplicationSettings), rs)
}

// GetReplicationSettings mocks base method
func (m *MockNodeReplicationController) GetReplicationSettings() (mysql.ReplicationSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReplicationSettings")
	ret0, _ := ret[0].(mysql.ReplicationSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReplicationSettings indicates an expected call of GetReplicationSettings
func (mr *MockNodeReplicationControllerMockRecorder) GetReplicationSettings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReplicationSettings", reflect.TypeOf((*MockNodeReplicationController)(nil).GetReplicationSettings))
}

// OptimizeReplication mocks base method
func (m *MockNodeReplicationController) OptimizeReplication() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OptimizeReplication")
	ret0, _ := ret[0].(error)
	return ret0
}

// OptimizeReplication indicates an expected call of OptimizeReplication
func (mr *MockNodeReplicationControllerMockRecorder) OptimizeReplication() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OptimizeReplication", reflect.TypeOf((*MockNodeReplicationController)(nil).OptimizeReplication))
}

// GetReplicaStatus mocks base method
func (m *MockNodeReplicationController) GetReplicaStatus() (mysql.ReplicaStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReplicaStatus")
	ret0, _ := ret[0].(mysql.ReplicaStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReplicaStatus indicates an expected call of GetReplicaStatus
func (mr *MockNodeReplicationControllerMockRecorder) GetReplicaStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReplicaStatus", reflect.TypeOf((*MockNodeReplicationController)(nil).GetReplicaStatus))
}

// Host mocks base method
func (m *MockNodeReplicationController) Host() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Host")
	ret0, _ := ret[0].(string)
	return ret0
}

// Host indicates an expected call of Host
func (mr *MockNodeReplicationControllerMockRecorder) Host() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Host", reflect.TypeOf((*MockNodeReplicationController)(nil).Host))
}

// MockCluster is a mock of Cluster interface
type MockCluster struct {
	ctrl     *gomock.Controller
	recorder *MockClusterMockRecorder
}

// MockClusterMockRecorder is the mock recorder for MockCluster
type MockClusterMockRecorder struct {
	mock *MockCluster
}

// NewMockCluster creates a new mock instance
func NewMockCluster(ctrl *gomock.Controller) *MockCluster {
	mock := &MockCluster{ctrl: ctrl}
	mock.recorder = &MockClusterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCluster) EXPECT() *MockClusterMockRecorder {
	return m.recorder
}

// GetNode mocks base method
func (m *MockCluster) GetNode(hostname string) NodeReplicationController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNode", hostname)
	ret0, _ := ret[0].(NodeReplicationController)
	return ret0
}

// GetNode indicates an expected call of GetNode
func (mr *MockClusterMockRecorder) GetNode(hostname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNode", reflect.TypeOf((*MockCluster)(nil).GetNode), hostname)
}

// GetState mocks base method
func (m *MockCluster) GetState(hostname string) node_state.NodeState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState", hostname)
	ret0, _ := ret[0].(node_state.NodeState)
	return ret0
}

// GetState indicates an expected call of GetState
func (mr *MockClusterMockRecorder) GetState(hostname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockCluster)(nil).GetState), hostname)
}

// GetMaster mocks base method
func (m *MockCluster) GetMaster() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaster")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetMaster indicates an expected call of GetMaster
func (mr *MockClusterMockRecorder) GetMaster() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaster", reflect.TypeOf((*MockCluster)(nil).GetMaster))
}
